### ISSUE TITLE
Not using history api back method?

### ISSUE THREAD

**Issue by che-effe** [erikringsmuth/pushstate-anchor#3]
Is there any way to include the same tie in to the historyAPI `.back()` method? Similar to the way you've incorporated it into `html5-history-anchor` via adding the `back` attribute to an anchor tag?

**Comment by erikringsmuth** [comment]
I *could* add it but ideally I want to leave this as a pure `history.pushState()` element. The goal is to have something similar to a link like this that triggers a `popstate` instead of a `hashchange`.

```html
<a href="#/home">back</a>
```

The back functionality is easy to implement with an event handler as well. I think even this would work.

```html
<a href="javascript:history.back()">back</a>
```

Or an event handler that calls `history.back()`.

**Comment by che-effe** [comment]
Thank you so much for the reply.  I love the implementation of going back via the 'back' attribute in html5-history-anchor. I may just replace pushtate-anchor with that so I can get the added functionality throughout the project. Cheers!
